name: CI
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  aws_amplify:
    name: CI
    uses: GabrielSoares-Dev/workflows/.github/workflows/angular-aws-amplify-CI.yml@master
    with:
      node_version: '18.x'
      work_dir: ./terraform
      environment: dev
      env_vars_path: env/dev.tfvars
    secrets:
      aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
      aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      git_hub_secret: ${{secrets.GIT_HUB_SECRET}}

