name: DEPLOY - DEV
on: 
   workflow_dispatch:
   push:
        branches:
         - master
env:
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    TF_VAR_repository: ${{secrets.REPOSITORY}}
    TF_VAR_access_token: ${{secrets.GIT_HUB_SECRET}}
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
        run:
          shell: bash
          working-directory: ./terraform
    steps:
       - name: Checkout
         uses: actions/checkout@v3
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3
         with:
          terraform_version: "1.2.0"
          terraform_wrapper: false
       - name: Init
         run: terraform init
       - name: Validate
         run: terraform validate
       - name: Select workspace
         run: terraform workspace select dev
       - name: Plan
         run: terraform plan -out plan.out
       - name: Apply
         id: apply
         run: terraform apply plan.out
       - name: Export outputs
         id: export_outputs
         run: terraform output webhook_trigger
       - name: Trigger update
         run:  curl -X POST -d {} "${{ steps.apply.outputs.webhook_trigger }}" -H "Content-Type:application/json"
         
