name: DEPLOY - STG
on:
  workflow_dispatch:
jobs:
  aws_amplify:
    name: deploy
    uses: GabrielSoares-Dev/workflows/.github/workflows/angular-aws-amplify-deploy.yml@master
    with:
      work_dir: ./terraform
      environment: stg
      env_vars_path: env/stg.tfvars
    secrets:
      aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID_STG}}
      aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY_STG}}
      git_hub_secret: ${{secrets.GIT_HUB_SECRET}}