name: DEPLOY - PROD
on:
  workflow_dispatch:
env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  TF_VAR_access_token: ${{secrets.GIT_HUB_SECRET}}
  TF_VAR_environment: PROD
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.2.0"
      - name: Init
        run: terraform init
      - name: Validate
        run: terraform validate
      - name: Select workspace
        run: terraform workspace select prod
      - name: Plan
        run: terraform plan -out plan.out
      - name: Apply
        run: terraform apply plan.out
      - name: Export outputs
        id: export_outputs
        run: |
          echo "WEBHOOK=$(terraform output -raw webhook_trigger)" >> $GITHUB_OUTPUT
      - name: Trigger update
        run: curl -X POST -d {} "${{ steps.export_outputs.outputs.WEBHOOK }}" -H "Content-Type:application/json"
